import "./index.scss"
export { default as Hero } from "./Hero/"
export { default as Statistics } from "./Statistics/"
export { default as EpisodesTypes } from "./EpisodesType/"
export { default as TopEpisodes } from "./TopEpisodes/"
export { default as Reviews } from "./Reviews"
export { default as Notification } from "./Notification/"
